### ISSUE TITLE
Bad indention when showing service actions

### ISSUE THREAD

**Issue by grimpy** [Jumpscale/portal9#28]
#### Installation information

- jumpscale version: master
- operating system: linux

#### Detailed description

See screenshot

#### Relevant stacktraces

![170702_093341](https://user-images.githubusercontent.com/143869/27768049-dd37b840-5f09-11e7-92b2-02c853648f46.png)

**Comment by ashraffouda** [comment]
https://github.com/Jumpscale/portal9/pull/29
