### ISSUE TITLE
Portal not to create "home" space by default

### ISSUE THREAD

**Issue by Dinaamagdy** [Jumpscale/portal9#38]
#### Installation information

- jumpscale version:
bc689e3b7d789ae5ef3be11d0989d674d27e1ef3

#### Detailed description
whem you click in  home , it will return you to empty page as shown in the attached image .
![selection_478](https://user-images.githubusercontent.com/24386802/28011403-7dd87204-6562-11e7-8100-09484cb0bf72.png)

#### Steps to reproduce
- click in left navigation menu
- choose home

**Comment by rkhamis** [comment]
That's because `home` is an empty space.

**Comment by rkhamis** [comment]
We could instead not create `home` by default.

**Comment by alichaddad** [comment]
Only system space is added by default to the portal
