### ISSUE TITLE
Can't create user from system portal

### ISSUE THREAD

**Issue by Dinaamagdy** [Jumpscale/portal9#39]
#### Installation information

- jumpscale version:
bc689e3b7d789ae5ef3be11d0989d674d27e1ef3

#### Detailed description
when you create user from system portal it results the following  error:
```
Param with name:domain is missing.
```
![selection_474](https://user-images.githubusercontent.com/24386802/28011646-55416c8c-6563-11e7-86a6-190a6ee1d213.png)

#### Steps to reproduce
-  from system portal ,get users page
-  try to create new user

**Comment by ahmedelsayed-93** [comment]
### software version
master c5f6651c9
