### ISSUE TITLE
Blueprints editor

### ISSUE THREAD

**Issue by rkhamis** [Jumpscale/portal9#5]
Currently the cockpit portal allows the user to read blueprints, but they should be editable as well. Note that editing these blueprints is not just adding a text editor. When saving changes to a blueprint the content should be validated as well.

**Comment by xmonader** [comment]
Implemented in https://github.com/Jumpscale/portal9/commit/02e4f862b091e2509b395920be0a85ddd3a314e6

**Comment by ahmedelsayed-93** [comment]
Validation doesn't work from quickBlueprint form or the blueprints list editor.

### software version
master  : c5f4a38
