### ISSUE TITLE
Import OS Templates/Images --- Feature Request

### ISSUE THREAD

**Issue by rainmanh** [Jumpscale/portal9#69]
Hi,
A Feature Request in the hope it makes sense.
A suggestion as it would be ideal from the Admin point of view (Admin Broker Portal) to have the capability of uploading The OS Templates/Images. (those would be img/qcow2 imaes KVM compatible.)

Many thanks

**Comment by rkhamis** [comment]
In all cases, this isn't relevant to this repo. Perhaps you meant https://github.com/0-complexity/openvcloud?

But to answer your question, @grimpy and myself don't think it's a doable FR. See docs of how to create the template https://github.com/zero-os/home/blob/master/docs/tutorials/Create_a_vdisk_Boot_Image.md
