### ISSUE TITLE
***error***: could not find macro datatables_use} 

### ISSUE THREAD

**Issue by john-kheir** [Jumpscale/portal9#74]
#### Installation information

- jumpscale version:
9.1.3
- operating system:
Ubuntu 16

#### Detailed description
Found this error in the admin page
![scr1](https://user-images.githubusercontent.com/15011431/30422716-14cb76a4-9941-11e7-9364-50245f6b09f4.png)

#### Steps to reproduce
No idea

**Comment by abdulrahmantkhalifa** [comment]
![image](https://user-images.githubusercontent.com/15012414/32046991-ea2b0f0c-ba44-11e7-93b1-f87ce003290b.png)


could not reproduce.
jumpscale version : 9.2.0
