### ISSUE TITLE
Parsing of links and images in portal

### ISSUE THREAD

**Issue by alichaddad** [Jumpscale/portal9#9]
#### Installation information

- jumpscale version:master 

#### Detailed description
The way we check on links and images in the portal wiki files needs to be changed, since some data is interpreted as links or images when it shouldn't be.
For example:
![wrongimages](https://user-images.githubusercontent.com/24762033/27010083-c5332c34-4e9c-11e7-8d60-033c4dac474d.png)
As seen above the path of the service is interpreted as an image.

**Comment by xmonader** [comment]
https://github.com/Jumpscale/portal9/commit/210b697606f15da726bd1c40b0191eb23a3d9253
https://github.com/Jumpscale/portal9/commit/506f52a31098a37c5378b90fa4de9cec64bca20b
