### ISSUE TITLE
Allow usage of remote AYS server

### ISSUE THREAD

**Issue by alichaddad** [Jumpscale/portal9#91]
#### Installation information

- jumpscale version:9.3.0
- operating system: Ubuntu

#### Detailed description
Currently to use a remote AYS instance with portal AYS client(`j.clients.atyourservice`) is needed which means that AYS should be installed locally first to connect to a remote AYS. The AYS actor should be revised to use a separate client to connect to AYS, see: https://github.com/Jumpscale/lib9/tree/master/JumpScale9Lib/clients/atyourservice

**Comment by yveskerwyn** [comment]
fixed verified in 9.2.1
